# Generated by Django 4.0 on 2022-02-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_menu_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cov_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('number', models.IntegerField()),
                ('alert', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cov_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temp', models.FloatField()),
                ('cov_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cov_data', to='test.cov_name')),
            ],
        ),
    ]
