# Generated by Django 4.0 on 2022-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_cov_name_cov_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cov_name',
            name='name_image',
            field=models.ImageField(blank=True, null=True, upload_to='cov-images'),
        ),
    ]
