# Generated by Django 4.0 on 2022-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0010_alter_cov_data_date_alter_cov_data_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cov_name',
            name='name_image',
            field=models.ImageField(blank=True, default='app/media/cov-images/unknown.png', null=True, upload_to='cov-images'),
        ),
    ]
