# Generated by Django 4.0 on 2022-02-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0012_alter_cov_name_name_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cov_name',
            name='name_image',
            field=models.ImageField(default='cov-images/unknown.png', upload_to='cov-images'),
        ),
    ]
